name: ecash_book
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_local_notifications: ^14.1.0
  sqflite: ^2.2.8+4
  get_cli: ^1.8.1
  flutter_tts: ^3.6.3
  path_provider: ^2.0.15
  timezone: ^0.9.2
  permission_handler: ^10.2.0
  flutter_screenutil: ^5.8.2
  animated_bottom_navigation_bar: ^1.2.0
  circular_reveal_animation: ^2.0.1
  flutter_spinbox: ^0.13.1
  intl: ^0.17.0
  day_night_time_picker: ^1.2.0+2
  timer_builder: ^2.0.0
  custom_timer: ^0.2.3
  path: ^1.8.3
  image_picker: ^0.8.7+5
  regexed_validator: ^2.0.0+1
  validatorless: ^1.2.3



  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
